[tool.poetry]
name = "penelope"
version = "0.1.0"
description = "Some text analysis utilities"
authors = ["Roger Mähler <roger.mahler@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
gensim = "^3.8.3"
numpy = "^1.19.2"
pandas = "^1.1.2"
bokeh = "^2.2.1"
sklearn = "^0.0"
lxml = "^4.5.2"
ipywidgets = "^7.5.1"
memoization = "^0.3.1"
spacy = "^2.3.2"
ftfy = "^5.8"
nltk = "^3.5"
wordcloud = "^1.8.0"
scipy = "^1.5.2"
requests = "^2.24.0"
smart_open = "^2.2.1"
statsmodels = "^0.12.0"
glove-python-binary = "^0.2.0"
textacy = "^0.10.1"
community = "^1.0.0-beta.1"
flake8 = "^3.8.3"
pydotplus = "^2.0.2"

[tool.poetry.dev-dependencies]
pytest = "^6.1.0"
rope = "^0.17.0"
pylint = "^2.6.0"
yapf = "^0.30.0"
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
